const config = require('config');
const bodyParser = require('body-parser');
const idx = require('idx');
const uuid = require('node-uuid');
const path = require('path');
const signale = require('../utils/signale');
const handle = require('../utils/handles');
const functions = require('../utils/functions');

module.exports = (app) => {
  const sessionIds = new Map();
  const serverConfig = config.get('server');
  const paramsConfig = config.get('params');
  const context = serverConfig.context;

  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded({ extended: true }));

  const handleEvent = (event) => {
    const senderId = idx(event, (_) => _.sender.id);
    const eventType = functions.eventType(event);

    signale.info({
      prefix: '[handleEvent] EVENT TYPE',
      message: eventType,
    });

    if (!sessionIds.has(senderId)) {
      sessionIds.set(senderId, uuid.v4());
    }

    switch (eventType) {
      case 'postback':
        handle.postback(senderId, event.postback);
        break;
      case 'quick_reply':
        handle.quickReply(senderId, event.message.quick_reply);
        break;
      case 'attachments':
        handle.attachments(senderId, event.message);
        break;
      case 'text':
        handle.message(senderId, event.message);
        break;
      default:
        // Event delivery and read
        break;
    }
  };

  /**
   * @swagger
   * definitions:
   *   get-webhook-400:
   *      type: object
   *      properties:
   *          message:
   *              type: string
   *          code:
   *              type: number
   *   get-webhook-409:
   *      type: object
   *      properties:
   *          message:
   *              type: string
   *          type:
   *              type: string
   *          code:
   *              type: number
   *          fbtrace_id:
   *              type: string
   */
  /**
   * @swagger
   * /webhook:
   *   get:
   *     tags:
   *       - Webhook
   *     name: Webhook to validate message.
   *     summary: Webhook to validate message.
   *     security:
   *       - bearerAuth: []
   *     consumes:
   *       - application/json
   *     produces:
   *       - application/json
   *     parameters:
   *       - name: hub.verify_token
   *         in: query
   *         type: string
   *         default: my_awesome_bot
   *         required: true
   *         description: Token of verification.
   *     responses:
   *       '200':
   *          description: Consulta satisfactoria - hub.challenge - Generated by the Messenger Platform. Contains the expected response.
   *       '400':
   *          description: Error token.
   *          schema:
   *              $ref: '#/definitions/get-webhook-400'
   *       '409':
   *          description: Error subscription.
   *          schema:
   *              $ref: '#/definitions/get-webhook-409'
   *       '5xx':
   *          description: Error generico en el servidor
   */
  app.get(encodeURI(`${context}/webhook/`), (req, res) => {
    if (req.query['hub.verify_token'] === paramsConfig.verifyToken) {
      setTimeout(() => {
        functions
          .doSubscribeRequest()
          .then((response) => {
            signale.success({
              prefix: `[subscribe] RESPONSE`,
              message: `Subscription result: ${response.success}`,
            });
            res.status(200).send(req.query['hub.challenge']);
          })
          .catch((error) => {
            signale.error({
              prefix: `[subscribe] ERROR`,
              message: error.message,
            });
            res.status(409).send(error);
          });
      }, 3000);
    } else {
      signale.error({
        prefix: '[webhook]',
        message: 'Error, wrong validation token',
      });
      res
        .status(400)
        .send({ code: 400, message: 'Error, wrong validation token' });
    }
  });

  app.post(encodeURI(`${context}/webhook/`), (req, res) => {
    try {
      const webhook_event = req.body.entry[0];
      if (webhook_event.messaging) {
        webhook_event.messaging.forEach((event) => {
          signale.success({
            prefix: '[webhook] EVENT RECEIVED',
            message: JSON.stringify(event),
          });
          handleEvent(event);
        });
      }
      res.status(200).send({ status: 'success' });
    } catch (err) {
      signale.error({
        prefix: '[webhook] ERROR',
        message: err,
      });
      res.status(400).send({ code: 400, message: err });
    }
  });

  /**
   * @swagger
   * definitions:
   *   post-message-200:
   *      type: object
   *      properties:
   *         recipient_id:
   *              type: string
   *         message_id:
   *              type: string
   *         attachment_id:
   *              type: string
   *   post-message-409:
   *      type: object
   *      properties:
   *          error:
   *              type: object
   *              properties:
   *                  message:
   *                      type: string
   *                  type:
   *                      type: string
   *                  code:
   *                      type: number
   *                  fbtrace_id:
   *                      type: string
   */
  /**
   * @swagger
   * /message:
   *   post:
   *     tags:
   *       - Messages
   *     name: Send message.
   *     summary: Send message.
   *     security:
   *       - bearerAuth: []
   *     consumes:
   *       - application/json
   *     produces:
   *       - application/json
   *     parameters:
   *       - name: recipientId
   *         in: query
   *         type: string
   *         default: 3172896426164477
   *         required: true
   *         description: id recipient.
   *       - name: templateMessage
   *         in: query
   *         type: string
   *         required: true
   *         description: template message to send.
   *         enum: [ "text", "attachment", "quickReply"]
   *     responses:
   *       '200':
   *          description: Consulta satisfactoria.
   *          schema:
   *              $ref: '#/definitions/post-message-200'
   *       '409':
   *          description: Error subscription.
   *          schema:
   *              $ref: '#/definitions/post-message-409'
   *       '5xx':
   *          description: Error generico en el servidor
   */
  app.post(encodeURI(`${context}/message`), (req, res) => {
    let recipientId = encodeURI(req.query.recipientId);
    let templateMessage = encodeURI(req.query.templateMessage);
    let messageData;
    switch (templateMessage) {
      case 'text':
        messageData = {
          recipient: {
            id: recipientId,
          },
          message: {
            text: 'Hola mundo!',
          },
        };
        break;
      case 'attachment':
        messageData = {
          recipient: {
            id: recipientId,
          },
          message: {
            attachment: {
              type: 'image',
              payload: {
                url: `https://images.unsplash.com/photo-1527430253228-e93688616381?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=891&q=80`,
                is_reusable: true,
              },
            },
          },
        };
        break;
      case 'quickReply':
        messageData = {
          recipient: {
            id: recipientId,
          },
          message: {
            text: 'Seleccione una opción',
            quick_replies: [
              {
                content_type: 'text',
                title: 'Opc 1',
                payload: 'OPC_1_PAYLOAD',
              },
              {
                content_type: 'text',
                title: 'Opc 2',
                payload: 'OPC_2_PAYLOAD',
                image_url:
                  'https://www.lavanguardia.com/r/GODO/LV/p5/WebSite/2018/06/22/Recortada/img_melies_20180622-173809_imagenes_lv_terceros_img_0691-knNG--656x656@LaVanguardia-Web.jpeg',
              },
              {
                content_type: 'text',
                title: 'Opc 3 🍀',
                payload: 'OPC_3_PAYLOAD',
              },
            ],
          },
        };
        break;
    }

    functions
      .sendMessage(messageData)
      .then((response) => {
        signale.success({
          prefix: `[sendMessage] RESPONSE`,
          message: response,
        });
        res.status(200).send(response);
      })
      .catch((error) => {
        signale.error({
          prefix: `[sendMessage] ERROR`,
          message: error,
        });
        res.status(409).send(error);
      });
  });
};
